<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../build/ImprovedGarrisons.CoopIntegration/Core/*.cs"
             Link="IntegrationCore/%(Filename)%(Extension)"
             Condition="Exists('../../build/ImprovedGarrisons.CoopIntegration/Core')" />
  </ItemGroup>
</Project>
